/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type OcspUpdateOptions struct {
	Disable bool `json:"disable,omitempty"`
	Httpproxy *OcspUpdateOptionsHttpproxy `json:"httpproxy,omitempty"`
	// Sets the maximum interval between two automatic updates of the same OCSP response.This time is expressed in seconds
	Maxdelay int32 `json:"maxdelay,omitempty"`
	// Sets the minimum interval between two automatic updates of the same OCSP response. This time is expressed in seconds
	Mindelay int32 `json:"mindelay,omitempty"`
	Mode string `json:"mode,omitempty"`
}
