/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dataplaneclient

type SslOptions struct {
	CaBase                     string              `json:"ca_base,omitempty"`
	CrtBase                    string              `json:"crt_base,omitempty"`
	DefaultBindCiphers         string              `json:"default_bind_ciphers,omitempty"`
	DefaultBindCiphersuites    string              `json:"default_bind_ciphersuites,omitempty"`
	DefaultBindClientSigalgs   string              `json:"default_bind_client_sigalgs,omitempty"`
	DefaultBindCurves          string              `json:"default_bind_curves,omitempty"`
	DefaultBindOptions         string              `json:"default_bind_options,omitempty"`
	DefaultBindSigalgs         string              `json:"default_bind_sigalgs,omitempty"`
	DefaultServerCiphers       string              `json:"default_server_ciphers,omitempty"`
	DefaultServerCiphersuites  string              `json:"default_server_ciphersuites,omitempty"`
	DefaultServerClientSigalgs string              `json:"default_server_client_sigalgs,omitempty"`
	DefaultServerCurves        string              `json:"default_server_curves,omitempty"`
	DefaultServerOptions       string              `json:"default_server_options,omitempty"`
	DefaultServerSigalgs       string              `json:"default_server_sigalgs,omitempty"`
	DhParamFile                string              `json:"dh_param_file,omitempty"`
	Engines                    []SslOptionsEngines `json:"engines,omitempty"`
	IssuersChainPath           string              `json:"issuers_chain_path,omitempty"`
	LoadExtraFiles             string              `json:"load_extra_files,omitempty"`
	Maxsslconn                 int32               `json:"maxsslconn,omitempty"`
	Maxsslrate                 int32               `json:"maxsslrate,omitempty"`
	ModeAsync                  string              `json:"mode_async,omitempty"`
	Propquery                  string              `json:"propquery,omitempty"`
	Provider                   string              `json:"provider,omitempty"`
	ProviderPath               string              `json:"provider_path,omitempty"`
	SecurityLevel              int32               `json:"security_level,omitempty"`
	ServerVerify               string              `json:"server_verify,omitempty"`
	SkipSelfIssuedCa           bool                `json:"skip_self_issued_ca,omitempty"`
}
