/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dataplaneclient

type HttpClientOptions struct {
	ResolversDisabled string `json:"resolvers_disabled,omitempty"`
	ResolversId       string `json:"resolvers_id,omitempty"`
	ResolversPrefer   string `json:"resolvers_prefer,omitempty"`
	Retries           int32  `json:"retries,omitempty"`
	SslCaFile         string `json:"ssl_ca_file,omitempty"`
	SslVerify         string `json:"ssl_verify,omitempty"`
	TimeoutConnect    int32  `json:"timeout_connect,omitempty"`
}
