/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// This field is deprecated in favor of force_persist_list, and will be removed in a future release
type BackendBaseForcePersist struct {
	Cond string `json:"cond"`
	CondTest string `json:"cond_test"`
}
