/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TuneSslOptions struct {
	Cachesize int32 `json:"cachesize,omitempty"`
	CaptureBufferSize int32 `json:"capture_buffer_size,omitempty"`
	CtxCacheSize int32 `json:"ctx_cache_size,omitempty"`
	DefaultDhParam int32 `json:"default_dh_param,omitempty"`
	ForcePrivateCache bool `json:"force_private_cache,omitempty"`
	Keylog string `json:"keylog,omitempty"`
	Lifetime int32 `json:"lifetime,omitempty"`
	Maxrecord int32 `json:"maxrecord,omitempty"`
	OcspUpdateMaxDelay int32 `json:"ocsp_update_max_delay,omitempty"`
	OcspUpdateMinDelay int32 `json:"ocsp_update_min_delay,omitempty"`
}
