/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TuneOptions struct {
	AppletZeroCopyForwarding string `json:"applet_zero_copy_forwarding,omitempty"`
	CompMaxlevel int32 `json:"comp_maxlevel,omitempty"`
	DisableZeroCopyForwarding bool `json:"disable_zero_copy_forwarding,omitempty"`
	EventsMaxEventsAtOnce int32 `json:"events_max_events_at_once,omitempty"`
	FailAlloc bool `json:"fail_alloc,omitempty"`
	FdEdgeTriggered string `json:"fd_edge_triggered,omitempty"`
	H1ZeroCopyFwdRecv string `json:"h1_zero_copy_fwd_recv,omitempty"`
	H1ZeroCopyFwdSend string `json:"h1_zero_copy_fwd_send,omitempty"`
	H2BeGlitchesThreshold int32 `json:"h2_be_glitches_threshold,omitempty"`
	H2BeInitialWindowSize int32 `json:"h2_be_initial_window_size,omitempty"`
	H2BeMaxConcurrentStreams int32 `json:"h2_be_max_concurrent_streams,omitempty"`
	H2FeGlitchesThreshold int32 `json:"h2_fe_glitches_threshold,omitempty"`
	H2FeInitialWindowSize int32 `json:"h2_fe_initial_window_size,omitempty"`
	H2FeMaxConcurrentStreams int32 `json:"h2_fe_max_concurrent_streams,omitempty"`
	H2FeMaxTotalStreams int32 `json:"h2_fe_max_total_streams,omitempty"`
	H2HeaderTableSize int32 `json:"h2_header_table_size,omitempty"`
	H2InitialWindowSize int32 `json:"h2_initial_window_size,omitempty"`
	H2MaxConcurrentStreams int32 `json:"h2_max_concurrent_streams,omitempty"`
	H2MaxFrameSize int32 `json:"h2_max_frame_size,omitempty"`
	H2ZeroCopyFwdSend string `json:"h2_zero_copy_fwd_send,omitempty"`
	HttpCookielen int32 `json:"http_cookielen,omitempty"`
	HttpLogurilen int32 `json:"http_logurilen,omitempty"`
	HttpMaxhdr int32 `json:"http_maxhdr,omitempty"`
	IdlePoolShared string `json:"idle_pool_shared,omitempty"`
	Idletimer int32 `json:"idletimer,omitempty"`
	ListenerDefaultShards string `json:"listener_default_shards,omitempty"`
	ListenerMultiQueue string `json:"listener_multi_queue,omitempty"`
	MaxChecksPerThread int32 `json:"max_checks_per_thread,omitempty"`
	Maxaccept int32 `json:"maxaccept,omitempty"`
	Maxpollevents int32 `json:"maxpollevents,omitempty"`
	Maxrewrite int32 `json:"maxrewrite,omitempty"`
	MemoryHotSize int32 `json:"memory_hot_size,omitempty"`
	PatternCacheSize int32 `json:"pattern_cache_size,omitempty"`
	PeersMaxUpdatesAtOnce int32 `json:"peers_max_updates_at_once,omitempty"`
	PoolHighFdRatio int32 `json:"pool_high_fd_ratio,omitempty"`
	PoolLowFdRatio int32 `json:"pool_low_fd_ratio,omitempty"`
	PtZeroCopyForwarding string `json:"pt_zero_copy_forwarding,omitempty"`
	RingQueues int32 `json:"ring_queues,omitempty"`
	RunqueueDepth int32 `json:"runqueue_depth,omitempty"`
	SchedLowLatency string `json:"sched_low_latency,omitempty"`
	StickCounters int32 `json:"stick_counters,omitempty"`
}
