/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TuneQuicOptions struct {
	FrontendConnTxBuffersLimit int32 `json:"frontend_conn_tx_buffers_limit,omitempty"`
	FrontendMaxIdleTimeout int32 `json:"frontend_max_idle_timeout,omitempty"`
	FrontendMaxStreamsBidi int32 `json:"frontend_max_streams_bidi,omitempty"`
	MaxFrameLoss int32 `json:"max_frame_loss,omitempty"`
	ReorderRatio int32 `json:"reorder_ratio,omitempty"`
	RetryThreshold int32 `json:"retry_threshold,omitempty"`
	SocketOwner string `json:"socket_owner,omitempty"`
	ZeroCopyFwdSend string `json:"zero_copy_fwd_send,omitempty"`
}
