/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Userlist with all it's children resources
type Userlist struct {
	Name string `json:"name"`
	Groups interface{} `json:"groups,omitempty"`
	Users interface{} `json:"users,omitempty"`
}
