/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dataplaneclient

// HAProxy global configuration
type GlobalBase struct {
	Chroot                                 string                       `json:"chroot,omitempty"`
	CloseSpreadTime                        int32                        `json:"close_spread_time,omitempty"`
	ClusterSecret                          string                       `json:"cluster_secret,omitempty"`
	CpuMaps                                []GlobalBaseCpuMaps          `json:"cpu_maps,omitempty"`
	Daemon                                 bool                         `json:"daemon,omitempty"`
	DebugOptions                           *DebugOptions                `json:"debug_options,omitempty"`
	DefaultPath                            *GlobalBaseDefaultPath       `json:"default_path,omitempty"`
	Description                            string                       `json:"description,omitempty"`
	DeviceAtlasOptions                     *DeviceAtlasOptions          `json:"device_atlas_options,omitempty"`
	EnvironmentOptions                     *EnvironmentOptions          `json:"environment_options,omitempty"`
	ExposeExperimentalDirectives           bool                         `json:"expose_experimental_directives,omitempty"`
	ExternalCheck                          bool                         `json:"external_check,omitempty"`
	FiftyOneDegreesOptions                 *FiftyOneDegreesOptions      `json:"fifty_one_degrees_options,omitempty"`
	Gid                                    int32                        `json:"gid,omitempty"`
	Grace                                  int32                        `json:"grace,omitempty"`
	Group                                  string                       `json:"group,omitempty"`
	H1AcceptPayloadWithAnyMethod           bool                         `json:"h1_accept_payload_with_any_method,omitempty"`
	H1CaseAdjust                           []GlobalBaseH1CaseAdjust     `json:"h1_case_adjust,omitempty"`
	H1CaseAdjustFile                       string                       `json:"h1_case_adjust_file,omitempty"`
	H1DoNotCloseOnInsecureTransferEncoding bool                         `json:"h1_do_not_close_on_insecure_transfer_encoding,omitempty"`
	H2WorkaroundBogusWebsocketClients      bool                         `json:"h2_workaround_bogus_websocket_clients,omitempty"`
	HardStopAfter                          int32                        `json:"hard_stop_after,omitempty"`
	Harden                                 *GlobalBaseHarden            `json:"harden,omitempty"`
	HttpClientOptions                      *HttpClientOptions           `json:"http_client_options,omitempty"`
	HttpErrCodes                           []HttpCodes                  `json:"http_err_codes,omitempty"`
	HttpFailCodes                          []HttpCodes                  `json:"http_fail_codes,omitempty"`
	InsecureForkWanted                     bool                         `json:"insecure_fork_wanted,omitempty"`
	InsecureSetuidWanted                   bool                         `json:"insecure_setuid_wanted,omitempty"`
	LimitedQuic                            bool                         `json:"limited_quic,omitempty"`
	Localpeer                              string                       `json:"localpeer,omitempty"`
	LogSendHostname                        *GlobalBaseLogSendHostname   `json:"log_send_hostname,omitempty"`
	LuaOptions                             *LuaOptions                  `json:"lua_options,omitempty"`
	MasterWorker                           bool                         `json:"master-worker,omitempty"`
	MworkerMaxReloads                      int32                        `json:"mworker_max_reloads,omitempty"`
	Nbthread                               int32                        `json:"nbthread,omitempty"`
	NoQuic                                 bool                         `json:"no_quic,omitempty"`
	Node                                   string                       `json:"node,omitempty"`
	NumaCpuMapping                         string                       `json:"numa_cpu_mapping,omitempty"`
	OcspUpdateOptions                      *OcspUpdateOptions           `json:"ocsp_update_options,omitempty"`
	PerformanceOptions                     *PerformanceOptions          `json:"performance_options,omitempty"`
	Pidfile                                string                       `json:"pidfile,omitempty"`
	Pp2NeverSendLocal                      bool                         `json:"pp2_never_send_local,omitempty"`
	PreallocFd                             bool                         `json:"prealloc_fd,omitempty"`
	RuntimeApis                            []interface{}                `json:"runtime_apis,omitempty"`
	SetDumpable                            bool                         `json:"set_dumpable,omitempty"`
	SetVar                                 []GlobalBaseSetVar           `json:"set_var,omitempty"`
	SetVarFmt                              []GlobalBaseSetVarFmt        `json:"set_var_fmt,omitempty"`
	Setcap                                 string                       `json:"setcap,omitempty"`
	SslOptions                             *SslOptions                  `json:"ssl_options,omitempty"`
	StatsFile                              string                       `json:"stats_file,omitempty"`
	StatsMaxconn                           int32                        `json:"stats_maxconn,omitempty"`
	StatsTimeout                           int32                        `json:"stats_timeout,omitempty"`
	StrictLimits                           bool                         `json:"strict_limits,omitempty"`
	ThreadGroupLines                       []GlobalBaseThreadGroupLines `json:"thread_group_lines,omitempty"`
	ThreadGroups                           int32                        `json:"thread_groups,omitempty"`
	TuneBufferOptions                      *TuneBufferOptions           `json:"tune_buffer_options,omitempty"`
	TuneLuaOptions                         *TuneLuaOptions              `json:"tune_lua_options,omitempty"`
	TuneOptions                            *TuneOptions                 `json:"tune_options,omitempty"`
	TuneQuicOptions                        *TuneQuicOptions             `json:"tune_quic_options,omitempty"`
	TuneSslOptions                         *TuneSslOptions              `json:"tune_ssl_options,omitempty"`
	TuneVarsOptions                        *TuneVarsOptions             `json:"tune_vars_options,omitempty"`
	TuneZlibOptions                        *TuneZlibOptions             `json:"tune_zlib_options,omitempty"`
	Uid                                    int32                        `json:"uid,omitempty"`
	UlimitN                                int32                        `json:"ulimit_n,omitempty"`
	User                                   string                       `json:"user,omitempty"`
	WurflOptions                           *WurflOptions                `json:"wurfl_options,omitempty"`
}
