/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dataplaneclient

type DebugOptions struct {
	Anonkey     int32 `json:"anonkey,omitempty"`
	Quiet       bool  `json:"quiet,omitempty"`
	ZeroWarning bool  `json:"zero_warning,omitempty"`
}
