/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PerformanceOptions struct {
	BusyPolling bool `json:"busy_polling,omitempty"`
	MaxSpreadChecks int32 `json:"max_spread_checks,omitempty"`
	Maxcompcpuusage int32 `json:"maxcompcpuusage,omitempty"`
	Maxcomprate int32 `json:"maxcomprate,omitempty"`
	Maxconn int32 `json:"maxconn,omitempty"`
	Maxconnrate int32 `json:"maxconnrate,omitempty"`
	Maxpipes int32 `json:"maxpipes,omitempty"`
	Maxsessrate int32 `json:"maxsessrate,omitempty"`
	Maxzlibmem int32 `json:"maxzlibmem,omitempty"`
	Noepoll bool `json:"noepoll,omitempty"`
	Noevports bool `json:"noevports,omitempty"`
	Nogetaddrinfo bool `json:"nogetaddrinfo,omitempty"`
	Nokqueue bool `json:"nokqueue,omitempty"`
	Nopoll bool `json:"nopoll,omitempty"`
	Noreuseport bool `json:"noreuseport,omitempty"`
	Nosplice bool `json:"nosplice,omitempty"`
	ProfilingMemory string `json:"profiling_memory,omitempty"`
	ProfilingTasks string `json:"profiling_tasks,omitempty"`
	ServerStateBase string `json:"server_state_base,omitempty"`
	ServerStateFile string `json:"server_state_file,omitempty"`
	SpreadChecks int32 `json:"spread_checks,omitempty"`
	ThreadHardLimit int32 `json:"thread_hard_limit,omitempty"`
}
