/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dataplaneclient

type TuneBufferOptions struct {
	BuffersLimit   int32 `json:"buffers_limit,omitempty"`
	BuffersReserve int32 `json:"buffers_reserve,omitempty"`
	Bufsize        int32 `json:"bufsize,omitempty"`
	Pipesize       int32 `json:"pipesize,omitempty"`
	RcvbufBackend  int32 `json:"rcvbuf_backend,omitempty"`
	RcvbufClient   int32 `json:"rcvbuf_client,omitempty"`
	RcvbufFrontend int32 `json:"rcvbuf_frontend,omitempty"`
	RcvbufServer   int32 `json:"rcvbuf_server,omitempty"`
	RecvEnough     int32 `json:"recv_enough,omitempty"`
	SndbufBackend  int32 `json:"sndbuf_backend,omitempty"`
	SndbufClient   int32 `json:"sndbuf_client,omitempty"`
	SndbufFrontend int32 `json:"sndbuf_frontend,omitempty"`
	SndbufServer   int32 `json:"sndbuf_server,omitempty"`
}
