/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs. 
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Loads a certificate from a store with options
type CrtLoad struct {
	// Certificate alias
	Alias string `json:"alias,omitempty"`
	// Certificate filename
	Certificate string `json:"certificate"`
	// OCSP issuer filename
	Issuer string `json:"issuer,omitempty"`
	// Private key filename
	Key string `json:"key,omitempty"`
	// OCSP response filename
	Ocsp string `json:"ocsp,omitempty"`
	// Automatic OCSP response update
	OcspUpdate string `json:"ocsp_update,omitempty"`
	// Signed Certificate Timestamp List filename
	Sctl string `json:"sctl,omitempty"`
}
