/*
 * HAProxy Data Plane API
 *
 * API for editing and managing haproxy instances. Provides process information, configuration management, haproxy stats and logs.
 *
 * API version: 3.0
 * Contact: support@haproxy.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package dataplaneclient

// Stick Table Information
type StickTable struct {
	Fields []StickTableFields `json:"fields,omitempty"`
	Name   string             `json:"name,omitempty"`
	Size   int32              `json:"size,omitempty"`
	Type_  string             `json:"type,omitempty"`
	Used   int32              `json:"used,omitempty"`
}
